---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apache-nifi.fullname" . }}-headless
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.headless.annotations }}
  annotations:
{{ toYaml .Values.headless.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.headless.type }}
  # It can be useful for setting up IP if we already have created Load Balancer
  # loadBalancerIP: {{ .Values.headless.ip }}
#  clusterIP: None
  ports:
{{- if .Values.properties.clusterSecure }}
  - port: {{ .Values.properties.httpsPort }}
    name: https
    nodePort: {{ .Values.properties.nodePort }}
  {{- else}}
  - port: {{ .Values.properties.httpPort }}
    name: http
{{- end }}
  - port: {{ .Values.properties.clusterPort }}
    name: cluster
  - port: 9092
    name: metrics
  selector:
    app: {{ include "apache-nifi.name" . | quote }}
    release: {{ .Release.Name | quote }}
