---
{{- if .Values.customStorageClass -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storageClass }}-{{ template "apache-nifi.fullname" . }}
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
provisioner: {{ .Values.storageProvisioner | quote }}
parameters:
  type: {{ .Values.storageType | quote }}
{{- end -}}