---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-registry-authorizers
  labels:
    app: {{ include "nifireg.fullname" . | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  authorizers.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <authorizers>

        <userGroupProvider>
         <identifier>ldap-user-group-provider</identifier>
            <class>org.apache.nifi.registry.security.ldap.tenants.LdapUserGroupProvider</class>
            <property name="Authentication Strategy">LDAPS</property>
            <property name="Manager DN">{{ .Values.auth.ldap.managerDn }}</property>
            <property name="Manager Password">{{ .Values.auth.ldap.password }}</property>
            <property name="Url">{{ .Values.auth.ldap.host }}</property>
            <property name="Referral Strategy">FOLLOW</property>

            <property name="TLS - Keystore">/opt/nifi-registry/nifi-registry-current/conf/keystore.jks</property>
            <property name="TLS - Keystore Password"></property>
            <property name="TLS - Keystore Type">JKS</property>
            <property name="TLS - Truststore">/opt/nifi-registry/nifi-registry-current/conf/truststore.jks</property>
            <property name="TLS - Truststore Password"></property>
            <property name="TLS - Truststore Type">JKS</property>
            <property name="TLS - Client Auth">WANT</property>
            <property name="TLS - Protocol">TLS</property>
            <property name="TLS - Shutdown Gracefully"></property>

            <property name="Connect Timeout">10 secs</property>
            <property name="Read Timeout">10 secs</property>
            <property name="Sync Interval">30 mins</property>

            <property name="User Search Base">dc=getindata,dc=com,dc=pl</property>
            <property name="User Search Scope">ONE_LEVEL</property>
            <property name="User Object Class">person</property>
            <property name="User Search Filter"></property>
            <property name="Identity Strategy">USE_USERNAME</property>

            <property name="Group Search Base">dc=getindata,dc=com,dc=pl</property>
            <property name="Group Object Class">group</property>
            <property name="Group Search Scope">ONE_LEVEL</property>
            <property name="Group Search Filter"></property>
            <property name="Group Name Attribute">cn</property>
            <property name="Group Member Attribute">member</property>
            <property name="Group Member Attribute - Referenced User Attribute"></property>
            <property name="Authentication Expiration">12 hours</property>
        </userGroupProvider>
        <authorizer>
            <identifier>ranger-authorizer</identifier>
            <class>org.apache.nifi.registry.ranger.RangerAuthorizer</class>
            <property name="Ranger Service Type">nifi-registry</property>
            <property name="User Group Provider">ldap-user-group-provider</property>
            <property name="Ranger Application Id">nifi-registry</property>
            <property name="Ranger Security Config Path">./conf/ranger-nifi-registry-security.xml</property>
            <property name="Ranger Audit Config Path">./conf/ranger-nifi-registry-audit.xml</property>
           <property name="Ranger Admin Identity">CN=ranger, OU=NIFI</property>
        </authorizer>

    </authorizers>
