{{ $nifi_root := printf "%s%s" "/opt/nifi-registry/nifi-registry-" .Values.image.tag }}
apiVersion: apps/v1
kind: Statefulset
metadata:
  name: {{ template "nifireg.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    date: {{ now | htmlDate }}
  labels:
    app: {{ template "nifireg.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    date: {{ now | htmlDate }}
spec:
  podManagementPolicy: {{ .Values.sts.podManagementPolicy }}
  serviceName: {{ template "nifireg.fullname" . }}-headless
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "nifireg.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nifireg.fullname" . }}
        release: {{ .Release.Name }}
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
    spec:
      dnsPolicy: {{ .Values.dnsPolicy |default "ClusterFirst" }}
      volumes:
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
{{- end }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: registry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: NIFIREG_GIT_REPO_PROTO
              value: "https://"
            - name: NIFIREG_GIT_REPO_URI
              value: {{ .Values.config.git.address }}
            - name: NIFIREG_GIT_REPO
              value: {{ .Values.config.git.repo }}
            - name: NIFI_REGISTRY_GIT_USER
              valueFrom:
                secretKeyRef:
                  name: nifiregistrypass
                  key: username
            - name: NIFI_REGISTRY_GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nifiregistrypass
                  key: password
            - name: KEY_STORE_PASSWD
              valueFrom:
                secretKeyRef:
                  name: nifi-registry-certs-passwd
                  key: KEY_STORE_PASSWD
            - name: KEY_PASSWD
              valueFrom:
                secretKeyRef:
                  name: nifi-registry-certs-passwd
                  key: KEY_PASSWD
            - name: TRUST_STORE_PASSWD
              valueFrom:
                secretKeyRef:
                  name: nifi-registry-certs-passwd
                  key: TRUST_STORE_PASSWD
          command:
            - /bin/bash
            - -c
            - |

              set -x
              set -e
              NIFI_REGISTRY_HOME=/opt/nifi-registry/nifi-registry-current

              echo 'Create directory for Apache Ranger policy cache...'
              touch /etc/ranger/nifi-registry/policycache/nifi-registry.json

              echo '...0'
              cd ${NIFI_REGISTRY_HOME}
              echo 'done...0'

              echo '...1'
              cd ./git_storage

              git config --global http.sslverify "false"

              if [[ -d "${NIFIREG_GIT_REPO}" ]]; then
                echo 'There is cloned Git repo(s)'
                cd ${NIFIREG_GIT_REPO}
                git pull
              else
                echo 'Cloning the Git repository...'
                git clone "https://${NIFI_REGISTRY_GIT_USER}:${NIFI_REGISTRY_GIT_PASSWORD}@${NIFIREG_GIT_REPO_URI}/${NIFIREG_GIT_REPO}.git"
              fi

              ls -la
              echo 'done...1'

              prop_replace () {
                target_file=${NIFI_REGISTRY_HOME}/conf/nifi-registry.properties
                echo "updating ${1} in ${target_file}"
                if egrep "^${1}=" ${target_file} &> /dev/null; then
                sed -i -e "s|^$1=.*$|$1=$2|"  ${target_file}
                else
                echo ${1}=${2} >> ${target_file}
                fi
              }         

              FQDN=$(hostname -f)
              cd ${NIFI_REGISTRY_HOME}

              NIFI_PROPS=${NIFI_REGISTRY_HOME}/conf/nifi-registry.properties
              NIFI_AUTHZ_FILE=${NIFI_REGISTRY_HOME}/conf/authorizers.xml
              NIFI_LOGIN_ID=${NIFI_REGISTRY_HOME}/conf/identity-providers.xml
              NIFI_KEY_STORE=${NIFI_REGISTRY_HOME}/conf/keystore.jks
              NIFI_KEY_STORE_TYPE=jks
              NIFI_KEY_STORE_PASSWORD=$KEY_STORE_PASSWD
              NIFI_KEY_PASSWORD=$KEY_PASSWD
              NIFI_TRUST_STORE=${NIFI_REGISTRY_HOME}/conf/truststore.jks
              NIFI_TRUST_STORE_TYPE=jks
              NIFI_TRUST_STORE_PASSWORD=$TRUST_STORE_PASSWD
              NIFI_INITIAL_ADMIN_IDENTITY=albert.lewandowski

              # Fix permissions
              cp ${NIFI_REGISTRY_HOME}/keystore.jks ${NIFI_REGISTRY_HOME}/conf/keystore.jks
              cp ${NIFI_REGISTRY_HOME}/truststore.jks ${NIFI_REGISTRY_HOME}/conf/truststore.jks

              cp ${NIFI_LOGIN_ID} ${NIFI_REGISTRY_HOME}/conf/new-identity-providers.xml
              sed -i -e 's|<property name="TLS - Keystore Password"></property>|<property name="TLS - Keystore Password">'"${NIFI_KEY_STORE_PASSWORD}"'</property>|'                       ${NIFI_REGISTRY_HOME}/conf/new-identity-providers.xml
              sed -i -e 's|<property name="TLS - Truststore Password"></property>|<property name="TLS - Truststore Password">'"${NIFI_TRUST_STORE_PASSWORD}"'</property>|'                 ${NIFI_REGISTRY_HOME}/conf/new-identity-providers.xml                                                                                                                      ${NIFI_REGISTRY_HOME}/conf/new-identity-providers.xml

              sed -i -e 's|<property name="Remote Access User"></property>|<property name="Remote Access User">'"${NIFI_REGISTRY_GIT_USER}"'</property>|'                 ${NIFI_REGISTRY_HOME}/conf/new-identity-providers.xml
              sed -i -e 's|<property name="Remote Access User"></property>|<property name="Remote Access Password">'"${NIFI_REGISTRY_GIT_PASSWORD}"'</property>|'                 ${NIFI_REGISTRY_HOME}/conf/new-identity-providers.xml

              cat "${NIFI_REGISTRY_HOME}/conf/nifi-registry.temp" > "${NIFI_REGISTRY_HOME}/conf/nifi-registry.properties"
              cat "${NIFI_REGISTRY_HOME}/conf/authorizers.temp" > "${NIFI_REGISTRY_HOME}/conf/authorizers.xml"

              {{- if .Values.config.security.https.enabled }}
              prop_replace nifi.registry.security.keystore                 ${NIFI_KEY_STORE}
              prop_replace nifi.registry.security.keystoreType             ${NIFI_KEY_STORE_TYPE}
              prop_replace nifi.registry.security.keystorePasswd           ${NIFI_KEY_STORE_PASSWORD}
              prop_replace nifi.registry.security.keyPasswd                ${NIFI_KEY_PASSWORD}
              prop_replace nifi.registry.security.truststore               ${NIFI_TRUST_STORE}
              prop_replace nifi.registry.security.truststoreType           ${NIFI_TRUST_STORE_TYPE}
              prop_replace nifi.registry.security.truststorePasswd         ${NIFI_TRUST_STORE_PASSWORD}

              # Set up TLS
              sed -i -e 's|<property name="TLS - Keystore Password"></property>|<property name="TLS - Keystore Password">'"${NIFI_KEY_STORE_PASSWORD}"'</property>|' ${NIFI_AUTHZ_FILE}
              sed -i -e 's|<property name="TLS - Truststore Password"></property>|<property name="TLS - Truststore Password">'"${NIFI_TRUST_STORE_PASSWORD}"'</property>|' ${NIFI_AUTHZ_FILE}
              {{- end }}

              ${NIFI_REGISTRY_HOME}/bin/nifi-registry.sh start
              tail -F "${NIFI_REGISTRY_HOME}/logs/nifi-registry-app.log" &
              nifi_registry_pid="$!"

              trap "echo Received trapped signal, beginning shutdown...;" KILL TERM HUP INT EXIT;

              echo NiFi-Registry running with PID ${nifi_registry_pid}.
              wait ${nifi_registry_pid}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            {{- if .Values.config.security.https.enabled }}
            - name: {{ .Values.portName | default "https" }}
              containerPort: {{ .Values.config.ports.https }}
              protocol: TCP
            {{- else }}
            - name: {{ .Values.portName | default "http" }}
              containerPort: {{ .Values.config.ports.http }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            - name: nifi-registry-authorizers
              mountPath: /opt/nifi-registry/nifi-registry-current/conf/authorizers.temp
              subPath: authorizers.xml
            - name: nifi-registry-bootstrap
              mountPath: /opt/nifi-registry/nifi-registry-current/conf/bootstrap.conf
              subPath: bootstrap.conf
            - name: nifi-registry-identity
              mountPath: /opt/nifi-registry/nifi-registry-current/conf/identity-providers.xml
              subPath: identity-providers.xml
            - name: krb5-conf
              mountPath: /etc/krb5.conf
              subPath: krb5.conf
            - name: nifi-registry-logback
              mountPath: /opt/nifi-registry/nifi-registry-current/conf/logback.xml
              subPath: logback.xml
            - name: nifi-registry-properties
              mountPath: /opt/nifi-registry/nifi-registry-current/conf/nifi-registry.temp
              subPath: nifi-registry.properties
            - name: nifi-registry-providers
              mountPath: /opt/nifi-registry/nifi-registry-current/conf/providers.xml
              subPath: providers.xml
  {{- if .Values.auth.ranger.enabled }}
            - name: ranger-security
              mountPath: /opt/nifi-registry/nifi-registry-current/conf/ranger-nifi-registry-security.xml
              subPath: ranger-nifi-registry-security.xml
            - name: ranger-audit
              mountPath: /opt/nifi-registry/nifi-registry-current/conf/ranger-nifi-registry-audit.xml
              subPath: ranger-nifi-registry-audit.xml
  {{- end }}
            - name: truststore
              mountPath: /opt/nifi-registry/nifi-registry-current/truststore.jks
              subPath: truststore.jks
            - name: keystore
              mountPath: /opt/nifi-registry/nifi-registry-current/keystore.jks
              subPath: keystore.jks
