name: Helm Test

on:
  push:
    paths:
      - 'apache-nifi-registry/chart/**'
  pull_request:
    branches:
      - develop
      - main

jobs:
  test-helm-nifireg:

    name: Run Helm templating and linter
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - name: Test NiFi Registry Helm chart
        uses: WyriHaximus/github-action-helm3@v2.0
        with:
          exec: helm lint apache-nifi-registry/chart && helm template --dry-run apache-nifi-registry/chart
